arb-dir: lib/l10n
output-dir: lib/l10n/generated
untranslated-messages-file: lib/l10n/missing_localizations.json
template-arb-file: test_task_app_en.arb
output-localization-file: test_task_app_localizations.dart
output-class: TestTaskAppLocalizations
preferred-supported-locales: "en"
synthetic-package: false
use-deferred-loading: false
nullable-getter: false
header: "// ignore_for_file: unnecessary_brace_in_string_interps, no_leading_underscores_for_local_identifiers"