name: test_task_bank
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  retrofit: ^4.1.0
  dio: ^5.5.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  injectable: ^2.4.2
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  auto_route: ^8.2.0
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  auto_route_generator: ^8.0.0

flutter:

  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
